--- # Final Assignment
- name: Final Assignment
  hosts: aws_ec2
  user: ubuntu
  become: yes
  gather_facts: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes